version: '3.7'

services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment: 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Had to use ip address here.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092 # And here too.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  units-api:
    build: ./Units
    ports: 
      - 3000:3000

  units-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  materials-api:
    build: ./Materials
    ports: 
      - 3001:3000

  materials-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example