version: '3.7'

services:
  units-api:
    build: ./Units
    ports: 
      - 3000:3000

  units-db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  materials-api:
    build: ./Materials
    ports: 
      - 3001:3000

  materials-db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example